// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NominalError {
    #[prost(enumeration = "GenericErrorE", tag = "1")]
    pub generic_error: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GenericErrorE {
    GenericerrorNone = 0,
    GenericerrorUnknown = 1,
    GenericerrorClosuresOpen = 2,
    GenericerrorAlreadyOn = 3,
    GenericerrorDisabledForUserCommand = 4,
    GenericerrorVehicleNotInPark = 5,
    GenericerrorUnauthorized = 6,
    GenericerrorNotAllowedOverTransport = 7,
}
impl GenericErrorE {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            GenericErrorE::GenericerrorNone => "GENERICERROR_NONE",
            GenericErrorE::GenericerrorUnknown => "GENERICERROR_UNKNOWN",
            GenericErrorE::GenericerrorClosuresOpen => "GENERICERROR_CLOSURES_OPEN",
            GenericErrorE::GenericerrorAlreadyOn => "GENERICERROR_ALREADY_ON",
            GenericErrorE::GenericerrorDisabledForUserCommand => {
                "GENERICERROR_DISABLED_FOR_USER_COMMAND"
            }
            GenericErrorE::GenericerrorVehicleNotInPark => {
                "GENERICERROR_VEHICLE_NOT_IN_PARK"
            }
            GenericErrorE::GenericerrorUnauthorized => "GENERICERROR_UNAUTHORIZED",
            GenericErrorE::GenericerrorNotAllowedOverTransport => {
                "GENERICERROR_NOT_ALLOWED_OVER_TRANSPORT"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GENERICERROR_NONE" => Some(Self::GenericerrorNone),
            "GENERICERROR_UNKNOWN" => Some(Self::GenericerrorUnknown),
            "GENERICERROR_CLOSURES_OPEN" => Some(Self::GenericerrorClosuresOpen),
            "GENERICERROR_ALREADY_ON" => Some(Self::GenericerrorAlreadyOn),
            "GENERICERROR_DISABLED_FOR_USER_COMMAND" => {
                Some(Self::GenericerrorDisabledForUserCommand)
            }
            "GENERICERROR_VEHICLE_NOT_IN_PARK" => {
                Some(Self::GenericerrorVehicleNotInPark)
            }
            "GENERICERROR_UNAUTHORIZED" => Some(Self::GenericerrorUnauthorized),
            "GENERICERROR_NOT_ALLOWED_OVER_TRANSPORT" => {
                Some(Self::GenericerrorNotAllowedOverTransport)
            }
            _ => None,
        }
    }
}
