// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Role {
    None = 0,
    Service = 1,
    Owner = 2,
    Driver = 3,
    Fm = 4,
    VehicleMonitor = 5,
    ChargingManager = 6,
    Guest = 8,
}
impl Role {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Role::None => "ROLE_NONE",
            Role::Service => "ROLE_SERVICE",
            Role::Owner => "ROLE_OWNER",
            Role::Driver => "ROLE_DRIVER",
            Role::Fm => "ROLE_FM",
            Role::VehicleMonitor => "ROLE_VEHICLE_MONITOR",
            Role::ChargingManager => "ROLE_CHARGING_MANAGER",
            Role::Guest => "ROLE_GUEST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROLE_NONE" => Some(Self::None),
            "ROLE_SERVICE" => Some(Self::Service),
            "ROLE_OWNER" => Some(Self::Owner),
            "ROLE_DRIVER" => Some(Self::Driver),
            "ROLE_FM" => Some(Self::Fm),
            "ROLE_VEHICLE_MONITOR" => Some(Self::VehicleMonitor),
            "ROLE_CHARGING_MANAGER" => Some(Self::ChargingManager),
            "ROLE_GUEST" => Some(Self::Guest),
            _ => None,
        }
    }
}
