// This file is @generated by prost-build.
/// The reasons why the site controller may recommend no charge.
/// The site controller will only return the highest priority reason to the vehicle.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChargeOnSolarNoChargeReason {
    Invalid = 0,
    /// The Powerwall is being prioritized over the vehicle to charge.
    PowerwallChargePriority = 1,
    /// There is not enough solar for the vehicle to charge effectively.
    InsufficientSolar = 2,
    /// The site controller is prioritizing export to the grid. This can
    /// happen when the site controller is in autonomous mode and it is
    /// most economical to export excess solar to the grid, or during a
    /// virtual power plant event.
    GridExportPriority = 3,
    /// Another vehicle is charging on solar at this location and has priority.
    AlternateVehicleChargePriority = 4,
}
impl ChargeOnSolarNoChargeReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ChargeOnSolarNoChargeReason::Invalid => {
                "CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID"
            }
            ChargeOnSolarNoChargeReason::PowerwallChargePriority => {
                "CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY"
            }
            ChargeOnSolarNoChargeReason::InsufficientSolar => {
                "CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR"
            }
            ChargeOnSolarNoChargeReason::GridExportPriority => {
                "CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY"
            }
            ChargeOnSolarNoChargeReason::AlternateVehicleChargePriority => {
                "CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY"
            }
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHARGE_ON_SOLAR_NO_CHARGE_REASON_INVALID" => Some(Self::Invalid),
            "CHARGE_ON_SOLAR_NO_CHARGE_REASON_POWERWALL_CHARGE_PRIORITY" => {
                Some(Self::PowerwallChargePriority)
            }
            "CHARGE_ON_SOLAR_NO_CHARGE_REASON_INSUFFICIENT_SOLAR" => {
                Some(Self::InsufficientSolar)
            }
            "CHARGE_ON_SOLAR_NO_CHARGE_REASON_GRID_EXPORT_PRIORITY" => {
                Some(Self::GridExportPriority)
            }
            "CHARGE_ON_SOLAR_NO_CHARGE_REASON_ALTERNATE_VEHICLE_CHARGE_PRIORITY" => {
                Some(Self::AlternateVehicleChargePriority)
            }
            _ => None,
        }
    }
}
